doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            experience_id: App\Experience\Infrastructure\Persistence\Type\ExperienceIdType
            provider_id: App\Experience\Infrastructure\Persistence\Type\ProviderIdType
            session_id: App\Experience\Infrastructure\Persistence\Type\SessionIdType
            reservation_id: App\Reservation\Infrastructure\Persistence\Type\ReservationIdType
            user_id: App\Reservation\Infrastructure\Persistence\Type\UserIdType
    orm:
        auto_mapping: false
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        mappings:
            Experience:
                type: xml
                dir: '%kernel.project_dir%/src/Experience/Infrastructure/Persistence/Mapping'
                prefix: 'App\Experience\Domain\Model'
                is_bundle: false
            Reservation:
                type: xml
                dir: '%kernel.project_dir%/src/Reservation/Infrastructure/Persistence/Mapping'
                prefix: 'App\Reservation\Domain\Model'
                is_bundle: false
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
